### ISSUE TITLE
Need Clarification 

### ISSUE THREAD

**Issue by abstractqqq** [conda-forge/polars-ds-feedstock#16]
### Comment:

@xhochy @thewchan 

I am very happy that you guys took the effort to publish the package on Conda. However, as the package owner and main developer I am not aware of this move.

Could you please answer some of my questions?

1. Could you please add me and any future maintainer of polars_ds to the maintainer list here upon request? 
2. As maintainers of this feedstock, what are the basic responsibilities? 
3. Could you please at least forward me a notice for any future change in this repo? Or before putting the package on any other platform? 

Thanks in advance.

**Comment by thewchan** [comment]
@abstractqqq 

1. Happy to add you as a maintainer to feedstock if you desire, just let us know
2. Mostly when upstream updates, the bot will attempt to fetch the new source and make a new PR. Usually there isn't a lot of manual steps needed except to update dependencies.
3. I don't think there will be any further change other than updating the version to match upstream

**Comment by abstractqqq** [comment]
> @abstractqqq 
> 
> 
> 
> 1. Happy to add you as a maintainer to feedstock if you desire, just let us know
> 
> 2. Mostly when upstream updates, the bot will attempt to fetch the new source and make a new PR. Usually there isn't a lot of manual steps needed except to update dependencies.
> 
> 3. I don't think there will be any further change other than updating the version to match upstream

Thank you! Yes please add me to the maintainer list!

**Comment by abstractqqq** [comment]
Thank you!
